spring:
  profiles:
    active: dev
logging:
  level:
    org.springframework.web: info
    org.springframework.boot: info
telegram:
  client:
    token: test
    username: test

# Dropbox Properties
dropbox:
  app:
    key: todo
    secret: todo
    redirectUri: http://localhost:8080/dropbox/finish-auth
    sessionStore:
      key: dropbox-auth-csrf-token