logging:
  level:
    root: warn
    org.springframework: info
    org.springframework.boot: info
    com.github.springtg.bot: debug
telegram:
  client:
    token: test
    username: test
    proxy:
      host:
      port: 8080
      nonProxyHosts: localhost