logging:
  level:
    root: warn
    org.springframework: info
    org.springframework.boot: info
    com.github.springtg.bot: debug
#telegram:
#  client:
#    proxy:
#      host: 127.0.0.1
#      port: 1080
#      proxyProtocol: SOCKS_V5
#      realmAuthScheme: BASIC
#      nonProxyHosts:
#        -localhost
# Dropbox Properties
dropbox:
  app:
    key: todo
    secret: todo
    redirectUri: http://localhost:8080/dropbox/finish-auth
    sessionStore:
      key: dropbox-auth-csrf-token